apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  type: LoadBalancer
  selector:
    app: python-deploy
  ports:
    - port: 3000
      targetPort: 3000
      # Optional field
      nodePort: 30007
